services:
  backend:
    image: ghcr.io/grid-sphere/career-counselling-backend:${IMAGE_TAG:-latest}
    container_name: career-counselling-backend
    restart: always

    env_file:
      - /root/career-counselling-backend/.env

    ports:
      - "6767:8000"